[package]
name = "pca9535"
version = "0.1.0"
edition = "2018"
authors = ["TeyKey1"]
repository = "https://github.com/TeyKey1/pca9535"
description = "PCA 9535 IO-Expander driver using embedded-hal"
readme = "README.md"
license = "MIT"

[dependencies]
embedded-hal = "=1.0.0-alpha.5"